export const GET_FUNNY_REQUEST = 'GET_FUNNY_REQUEST'
export const GET_FUNNY_SUCCESS = 'GET_FUNNY_SUCCESS'
export const GET_FUNNY_FAILED = 'GET_FUNNY_FAILED'

export const SEND_FUNNY_REQUEST = 'SEND_FUNNY_REQUEST'
export const SEND_FUNNY_SUCCESS = 'SEND_FUNNY_SUCCESS'
export const SEND_FUNNY_FAILED = 'SEND_FUNNY_FAILED'