// actionTypeは全部大文字で書く
export const ADD_NUMBER = 'ADD_NUMBER'
export const DECREASE_NUMBER = 'ECREASE_NUMBER'

export const GET_EXAMPLE_REQUEST = 'GET_EXAMPLE_REQUEST'
export const GET_EXAMPLE_SUCCESS = 'GET_EXAMPLE_SUCCESS'
export const GET_EXAMPLE_FAILED = 'GET_EXAMPLE_FAILED'

export const GET_TEXT_REQUEST = 'GET_TEXT_REQUEST'
export const GET_TEXT_SUCCESS = 'GET_TEXT_SUCCESS'
export const GET_TEXT_FAILED = 'GET_TEXT_FAILED'

export const GET_TEXT_ADD = 'GET_TEXT_ADD'

export const CREATE_USER = 'CREATE_USER'
