// actionTypeは全部大文字で書く
export const GET_WORKS_REQUEST = 'GET_WORKS_REQUEST'
export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS'
export const GET_WORKS_FAILED = 'GET_WORKS_FAILED'

export const POST_WORKS_REQUEST = 'POST_WORKS_REQUEST'
export const POST_WORKS_SUCCESS = 'POST_WORKS_SUCCESS'
export const POST_WORKS_FAILED = 'POST_WORKS_FAILED'
